# Generated by Django 2.1.3 on 2018-11-09 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Fruit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('amt', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='GithubLogs',
            fields=[
                ('id', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('mergeNumber', models.CharField(max_length=255)),
                ('author', models.CharField(max_length=255)),
                ('committer', models.CharField(max_length=255)),
                ('file', models.CharField(max_length=512)),
                ('additions', models.CharField(max_length=16)),
                ('deletions', models.CharField(max_length=16)),
                ('modifications', models.CharField(max_length=16)),
                ('sprint', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='JiraLogs',
            fields=[
                ('id', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('issueType', models.CharField(max_length=255)),
                ('priority', models.CharField(max_length=255)),
                ('key', models.CharField(max_length=255)),
                ('assignee', models.CharField(max_length=255)),
                ('sprint', models.CharField(max_length=255)),
                ('originalEstimate', models.CharField(max_length=255)),
                ('timeSpent', models.CharField(max_length=255)),
                ('status', models.CharField(max_length=255)),
                ('rca', models.CharField(max_length=512)),
            ],
        ),
        migrations.CreateModel(
            name='JiraLogSprintCompletion',
            fields=[
                ('id', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('key', models.CharField(max_length=255)),
                ('assignee', models.CharField(max_length=255)),
                ('sprint', models.CharField(max_length=255)),
                ('date', models.DateField(verbose_name='%Y-%m-%d')),
                ('timeSpent', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
            ],
        ),
    ]
